Repository qkeddy/travelcheck, pull requests merged in 2022-03, with the labels that each got.

#4 Stubbed out main functions to define working areas.
  assets/js/script.js
Labels: good first issue

#15 Feature/travel safety api initial build
  assets/js/script.js
Labels: MVP Build

#17 Nested the necessary functions into the respective fetch requests
  assets/js/script.js
Labels: bug

#23 Add event listener for the submit button and fixed spelling in HTML.
  assets/js/script.js
  index.html
Labels: MVP Build

#24 Feature/populate search function
  assets/js/script.js
  index.html
Labels: MVP Build

#29 Removed unnecessary logging
  assets/js/script.js
Labels: MVP Build
